
services:
  bigtop_hostname0:
    command: /sbin/init
    hostname: bigtop-hostname0
    container_name: bigtop_hostname0
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts

  bigtop_hostname1:
    command: /sbin/init
    hostname: bigtop-hostname1
    domainname: bigtop.apache.org
    container_name: bigtop_hostname1
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts

  bigtop_hostname2:
    command: /sbin/init
    hostname: bigtop-hostname2
    domainname: bigtop.apache.org
    container_name: bigtop_hostname2
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts

  bigtop_hostname3:
    command: /sbin/init
    hostname: bigtop-hostname3
    domainname: bigtop.apache.org
    container_name: bigtop_hostname3
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
